### PR TITLE
Artem

### PR DESCRIPTION
**Pull request by artemtar**

### CODE REVIEW

**Comment by artemtar** [comment]
hope it does not crush

**Comment by artemtar** [comment]
If you stack, or think qwinto is good enough, go to QwixxScoreBoard and figure out how to create Vector<QwixxRow<int, Color::C>> and same for list<>. This is the main part of Qwixx. Some code is started.
You can check my attempts to make vector there.

**Comment by artemtar** [comment]
and forgot to switch of main() in scoreshit , comment it out

**Review by Aleks048 — APPROVED** [review]
some work

**Pull request merged**
